title: "StationEntriesEtc"
author: "Eva Putnam"
date: "March 30, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```

```{r read in station entries}
gse_2013 <- read_csv("gated_station_entries_2013.csv")
gse_2014 <- read_csv("gated_station_entries_2014.csv")
gse_2015 <- read_csv("gated_station_entries_2015.csv")
gse_2016 <- read_csv("gated_station_entries_2016.csv")
gse_2017 <- read_csv("gated_station_entries_2017.csv")
gse_2018 <- read_csv("gated_station_entries_2018.csv")
```

```{r combine years of entries}
gse_all <- rbind(gse_2013, gse_2014, gse_2015, gse_2016, gse_2017, gse_2018) %>% select(station_name = STATION_NAME, date = DATE, time_period = TIME_PERIOD, station_entries = STATION_ENTRIES)
```


```{r sum entries by date and station}
#gse_daily_13 <- gse_2013 %>% group_by(date, station_name) %>% summarize(daily_entries = sum(station_entries))
gse_daily <- gse_all %>% group_by(date, station_name) %>% summarize(daily_entries = sum(station_entries))
```


```{r}
#gse_2013 %>% filter(DATE == "2013-09-01" & STATION_NAME == "Alewife")
```


```{r save backup}
gse_daily_2 <- gse_daily
```

```{r sum by week}
gse_weekly <- gse_daily_2 %>%
  mutate(year = as.numeric(format(date, '%Y'))) %>%
  group_by(station_name, week = week(date), year) %>%
  summarize(weekly_entries = sum(daily_entries))
```

```{r summary statistics for weekly entries}
summary(gse_weekly)
```


```{r read in fuel prices}
fuelprices <- read_csv("fuelprices.csv")
```


```{r reclass week as.date}
fuelprices$weekof <- as.Date(fuelprices$week, "%m-%d-%Y")
```

```{r number the weeks}
fp_weekly <- fuelprices %>%
  mutate(week = week(weekof), year = as.numeric(format(weekof, '%Y'))) 
```


```{r summary statistics for fuel prices}
summary(fuelprices)
```

```{r join gse_all and fuelprices}
gse_fp <- left_join(gse_weekly, fp_weekly, by = c("year", "week")) %>%
  select(station_name, week, year, fuel_price, weekly_entries, weekof) %>%
  arrange(year, week, station_name)
```

```{r read in ticket prices}

```



